name       : libcroco
version    : 0.6.12
release    : 8
source     :
    - https://ftp.gnome.org/pub/gnome/sources/libcroco/0.6/libcroco-0.6.12.tar.xz : ddc4b5546c9fb4280a5017e2707fbd4839034ed1aba5b7d4372212f34f84f860
license    : LGPL-2.0
summary    : Standalone CSS2 parsing and manipulation library
component  : desktop.library
builddeps  :
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(libxml-2.0)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
patterns   :
    - devel :
        - /usr/bin
optimize   : speed
description: |
    Libcroco is a standalone CSS2 parsing and manipulation library for the GNOME project, and allows for XML/CSS rendering.
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2017-7960.patch
    %patch -p1 < $pkgfiles/security/cve-2017-7961.patch
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
