name       : libcroco
version    : 0.6.13
release    : 10
source     :
    - https://download.gnome.org/sources/libcroco/0.6/libcroco-0.6.13.tar.xz : 767ec234ae7aa684695b3a735548224888132e063f92db585759b422570621d4
license    : LGPL-2.0-or-later
summary    : Standalone CSS2 parsing and manipulation library
description: |
    Libcroco is a standalone CSS2 parsing and manipulation library for the GNOME project, and allows for XML/CSS rendering.
component  : desktop.library
optimize   : speed
emul32     : yes
builddeps  :
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(libxml-2.0)
patterns   :
    - devel :
        - /usr/bin
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
