name        : libcroco
version     : 0.6.8
release     : 4
source      :
    - http://ftp.gnome.org/pub/gnome/sources/libcroco/0.6/libcroco-0.6.8.tar.xz : ea6e1b858c55219cefd7109756bff5bc1a774ba7a55f7d3ccd734d6b871b8570
license     :
    - LGPL-2.1
summary     : Standalone CSS2 parsing and manipulation library
component   : desktop.library
patterns    :
    - devel:
        - /usr/bin
optimize    : speed
description : |
    Libcroco is a standalone CSS2 parsing and manipulation library for the GNOME project, and allows for XML/CSS rendering.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
