name       : libcroco
version    : 0.6.11
release    : 6
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libcroco/0.6/libcroco-0.6.11.tar.xz : 132b528a948586b0dfa05d7e9e059901bca5a3be675b6071a90a90b81ae5a056
license    :
    - LGPL-2.1
summary    : Standalone CSS2 parsing and manipulation library
component  : desktop.library
builddeps  :
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(libxml-2.0)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
patterns   :
    - devel :
        - /usr/bin
optimize   : speed
description: |
    Libcroco is a standalone CSS2 parsing and manipulation library for the GNOME project, and allows for XML/CSS rendering.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
